### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by CleyLyChen** [gorjanradevski/multimodal-distillation#1] opened 2023-11-16 06:57 UTC
Hi! Great work!

I noticed that you released training code two weeks ago, but there haven't been updates to the relevant sections in the README. Could you confirm if this training code is usable? If so, could you provide the command used for training on the Epic-Kitchens dataset?

**Comment by yuezih** [comment] 2023-11-16 08:20
I have the same request 👀

**Comment by gorjanradevski** [comment] 2023-11-17 12:52
Hey @CleyLyChen, @yuezih, thanks for showing interest in our work! :) I'll make sure to release the code relevant for EPIC in a few days (after CVPR deadline, unfortunately)...I'll keep you posted!

**Comment by gorjanradevski** [comment] 2023-12-15 16:27
Hey, we've released the multimodal knowledge distillation training code. The only thing remaining to reproduce the experiments in our paper are the datasets (Epic-Kitchens, Something-Something/Else). We store these as large HDF5 files which we cannot upload anywhere (together they're around 1000GB). This gives us two options:

1. We provide you a link from our servers from where you can wget them.
2. We release a script, such that once you download Epic-Kitchens and Something-Something/Else, you can pack them as HDF5 files.

Let us know what do you prefer. Cheers!

**Comment by Alice123DH** [comment] 2023-12-27 16:25
Hi! Your work is very nice!
I found that there is no dataset. In the two options you provided, I hope that you can provide me a link of dataset from your servers from where I can wget them if it's convenient for you. Or could you please provide me with demo of dataset so that I can try to reproduce your work and learn from you. 
Thank you so much for your attention!

**Comment by Alice123DH** [comment] 2023-12-29 06:27
Hi! Your work is very nice!
I found that there is no dataset. In the two options you provided, I hope that you could provide the script. Because downloading the dataset of 1000GB  is too difficult for me. At the same time, I would be very grateful if you could provide me with demos of the dataset to help me reproduce the work and learn from you.
Thank you so much for your attention!

**Comment by gorjanradevski** [comment] 2024-01-04 15:10
@Alice123DH, @yuezih @CleyLyChen I can forward the datasets (HDF5) only via email using [Belnet](https://filesender.belnet.be/) so please post where should I send you the files.

**Comment by Alice123DH** [comment] 2024-01-05 16:51
Dear&nbsp;Gorjan，
&nbsp; &nbsp; Thank you so much for your asking. I received the dataset you sent on my 163 ***@***.***). I am truly grateful for your kindness, and&nbsp;thank you very much!




文津@
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gorjanradevski/multimodal-distillation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月4日(星期四) 晚上11:10
***@***.***&gt;;
抄送:&nbsp;"文津@***@***.******@***.***&gt;;
主题:&nbsp;Re: [gorjanradevski/multimodal-distillation] training code (Issue #1)





 
@Alice123DH, @yuezih @CleyLyChen I can forward the datasets (HDF5) only via email using Belnet so please post where should I send you the files.

**Comment by gorjanradevski** [comment] 2024-01-06 22:12
Update: I'll update the README by Friday next week with a permanent download link to obtain the HDF5 files for all datasets and modalities we use in the paper.

**Comment by gorjanradevski** [comment] 2024-01-14 10:04
We've just updated the README with a download link for the datasets. Closing this issue now.

**Closed as completed by gorjanradevski** 2024-01-14 10:04 UTC
